version: "3"
services:
  web:
    build: .
    ports:
      - "3099:3099"
    environment:
      - MONGO_URL=mongo
      - ELASTICSEARCH_URL=elasticsearch
    volumes :
       - .:/usr/src/app
    depends_on:
      - mongo
      - elasticsearch
        
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "5050:27017"
    
  elasticsearch: # Elasticsearch Instance
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    depends_on:
      - mongo
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    
volumes:
  elasticsearch-data:
    driver: local